// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3xGGnf5dW1sKKahhWHzBLY0AeQuW0kA',
    appId: '1:671797942909:web:7c1c57ef085b927f56af14',
    messagingSenderId: '671797942909',
    projectId: 'map-app-7c74e',
    authDomain: 'map-app-7c74e.firebaseapp.com',
    storageBucket: 'map-app-7c74e.firebasestorage.app',
    measurementId: 'G-7SWS7EJ9N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GS2hAjRBmwaTz04s1qE3dL1hXnCQdiw',
    appId: '1:671797942909:android:d279bd743641a8b356af14',
    messagingSenderId: '671797942909',
    projectId: 'map-app-7c74e',
    storageBucket: 'map-app-7c74e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOC2-qs5RKcCW56IQbQi1CyWvxUm9Cqfg',
    appId: '1:671797942909:ios:8147a894e0dee03456af14',
    messagingSenderId: '671797942909',
    projectId: 'map-app-7c74e',
    storageBucket: 'map-app-7c74e.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH3xGGnf5dW1sKKahhWHzBLY0AeQuW0kA',
    appId: '1:671797942909:web:b0870d6f95f25d8856af14',
    messagingSenderId: '671797942909',
    projectId: 'map-app-7c74e',
    authDomain: 'map-app-7c74e.firebaseapp.com',
    storageBucket: 'map-app-7c74e.firebasestorage.app',
    measurementId: 'G-8P2XE2NHDH',
  );
}
